name: blak smok
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '-g')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Apply patches
        continue-on-error: true
        run: |
          git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
          ./wyspigot patch
          tar -czf src.tar.gz WYSpIgot*
      - uses: actions/upload-artifact@v2
        with:
          name: blak-smok
          path: src.tar.gz
