name: Build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply patches
        run: ./wyspigot patch
      - name: blak smok
        run: tar -czf w.tar.gz WYSpIgot-*
      - uses: actions/upload-artifact@v2
        with:
          name: blak-smok
          path: w.tar.gz
