name: Build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: patch
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./wyspigot patch
      - name: paperclip
        run: ./wyspigot jar
      - name: release info
        id: relInfo
        run: |
          echo "::set-output name=date::$(date +'%H:%M %m/%d/%Y')"
          echo "::set-output name=shortHash::$(git rev-parse --short HEAD)"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "1.8.8"
          prerelease: false
          title: "WYSpIgot ${{ steps.relInfo.outputs.date }} ${{ steps.relInfo.outputs.shortHash }}"
          files: ./wyspigot-paperclip.jar
